// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdQy34RPn30yi-HKsC5Ebd1NsO8k0kYHY',
    appId: '1:416122152795:web:0ce0a66fb0f7b41c77dc7e',
    messagingSenderId: '416122152795',
    projectId: 'batch8wiederholung-24-4',
    authDomain: 'batch8wiederholung-24-4.firebaseapp.com',
    storageBucket: 'batch8wiederholung-24-4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDozC5--xR6b1_LXDzfYBTcrJtNAseBB-A',
    appId: '1:416122152795:android:c478288e7260971877dc7e',
    messagingSenderId: '416122152795',
    projectId: 'batch8wiederholung-24-4',
    storageBucket: 'batch8wiederholung-24-4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo1-9tmF8CvZv3LS4oq-9M36-pg__6x5E',
    appId: '1:416122152795:ios:d6a1d5458d2b64df77dc7e',
    messagingSenderId: '416122152795',
    projectId: 'batch8wiederholung-24-4',
    storageBucket: 'batch8wiederholung-24-4.firebasestorage.app',
    iosBundleId: 'com.example.batch8ProviderFirestore244',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo1-9tmF8CvZv3LS4oq-9M36-pg__6x5E',
    appId: '1:416122152795:ios:d6a1d5458d2b64df77dc7e',
    messagingSenderId: '416122152795',
    projectId: 'batch8wiederholung-24-4',
    storageBucket: 'batch8wiederholung-24-4.firebasestorage.app',
    iosBundleId: 'com.example.batch8ProviderFirestore244',
  );
}
