// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnglO3rh_i4QNrELbWMBJ5XhYsddSNNXE',
    appId: '1:548047765681:web:9c4825fd267bbac7a4a290',
    messagingSenderId: '548047765681',
    projectId: 'batch8-provider-test',
    authDomain: 'batch8-provider-test.firebaseapp.com',
    storageBucket: 'batch8-provider-test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpCIb1WiHdiaEavxSaya0g46dGobxbb_E',
    appId: '1:548047765681:android:222b0865e9042d74a4a290',
    messagingSenderId: '548047765681',
    projectId: 'batch8-provider-test',
    storageBucket: 'batch8-provider-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeSIMtUrNyYCybMdPydSxjA9HUfOrRpEw',
    appId: '1:548047765681:ios:52bfc08a4a2a75b4a4a290',
    messagingSenderId: '548047765681',
    projectId: 'batch8-provider-test',
    storageBucket: 'batch8-provider-test.firebasestorage.app',
    iosBundleId: 'com.example.batch8ProviderFirestore244',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeSIMtUrNyYCybMdPydSxjA9HUfOrRpEw',
    appId: '1:548047765681:ios:52bfc08a4a2a75b4a4a290',
    messagingSenderId: '548047765681',
    projectId: 'batch8-provider-test',
    storageBucket: 'batch8-provider-test.firebasestorage.app',
    iosBundleId: 'com.example.batch8ProviderFirestore244',
  );
}
